### ISSUE TITLE
봇 토큰 노출

### ISSUE THREAD

**Issue by cyoung06** [Team-Hwagong/Project-DW-Discord#2]
현제 봇 토큰이 config파일에 누출되어 있는것으로 보입니다.
.gitignore 을 이용해 그 파일만 제거하시고, 봇을 재 생성 하셔야 할것으로 보입니다

**Comment by endom4086** [comment]
급하게 여러 문제들을 지웠고, 개발자의 스케줄이 끝난 뒤 패치가 이루어질 예정입니다.
