### ISSUE TITLE
DB 로그인 정보 유출

### ISSUE THREAD

**Issue by cyoung06** [Team-Hwagong/Project-DW-Discord#3]
main.js에.. 아시겠죠?

db정보는 config.js 로 빼서, gitignore 설정하셔야 합니다. 유출되지 않게요

**Comment by hwahyang1** [comment]
History를 통하면 언제든지 SQL 접속이 가능한 상태입니다. 비밀번호 수정이 필요하여 보입니다.

**Comment by endom4086** [comment]
약 6시쯤 변경하겠습니다
변경후 이슈를 닫도록 하죠

**Comment by hwahyang1** [comment]
님 안닫으셨어요

**Comment by endom4086** [comment]
깜빡했음....
집에 가서 변경 예정입니다

**Comment by endom4086** [comment]
변경하였습니다.
추가로, 화향님 서버를 통해 이번 주 내로 DB 서버를 바꿀 예정이오니, 보안상의 문제는 어느정도 해결할 수 있다고 봅니다.
이슈 닫습니다.
